name: Test pull
on:
  pull_request:
    paths:
      - Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if image exists 
        run: |
          IMAGE_NAME=$(grep -m 1 '^FROM' Dockerfile | sed 's/^FROM\s*\(.*\)/\1/')
          echo "Checking image: $IMAGE_NAME"
          if docker manifest inspect $IMAGE_NAME > /dev/null 2>&1; then
            echo "Image exists"
          else
            echo "Image does not exist"
            exit 1
          fi